# Generated by Django 5.2.10 on 2026-01-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resumeanalysis_ats_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='ResumeAnalysis',
        ),
    ]
