# Generated by Django 5.2.10 on 2026-01-19 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='description',
            new_name='company_description',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='job_descriptions',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Skills (comma separated values)'),
        ),
    ]
