# Generated by Django 5.2.10 on 2026-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_description_recruiterprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
