# Generated by Django 5.2.10 on 2026-01-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_candidateprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='job_descriptions',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/', verbose_name='job Descriptiona must include job title, responsibilities, qualifications, benefits, locations etc.'),
        ),
    ]
