# Generated by Django 5.2.10 on 2026-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_candidateprofile_extracurricular_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='extracurricular_activities',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Educational qualifications', null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='Experience details', null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills', null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(blank=True, help_text='Description of the company'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text="Name of the recruiter's company", max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the company', max_length=255),
        ),
    ]
