# Generated by Django 5.2.10 on 2026-01-19 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_recruiterprofile_job_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
