# Generated by Django 5.2.10 on 2026-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_recruiterprofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.JSONField(blank=True, verbose_name='Skills (comma separated values)'),
        ),
    ]
