# Generated by Django 5.2.10 on 2026-01-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_candidateprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills (comma separated values)'),
        ),
    ]
