# Generated by Django 5.2.10 on 2026-01-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_candidateprofile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the job position', max_length=255)),
                ('job_description', models.TextField(blank=True, help_text='Detailed job description', null=True)),
                ('skills_required', models.JSONField(blank=True, default=list, help_text='List of required skills', null=True)),
                ('experience_required', models.CharField(help_text='Experience level required for the job', max_length=100)),
                ('location', models.CharField(help_text='Job location', max_length=255)),
                ('salary_range', models.CharField(help_text='Salary range for the job position', max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('job_status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.recruiterprofile')),
            ],
        ),
    ]
