# Generated by Django 5.2.10 on 2026-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_salary_range_job_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number_of_openings',
            field=models.IntegerField(default=1, help_text='Number of openings for the job position'),
        ),
    ]
