# Generated by Django 5.2.10 on 2026-01-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='raw_text',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='summary',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
