# Generated by Django 5.2.10 on 2026-01-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resumeanalysis_raw_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='is_parsed',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='updated_at',
        ),
    ]
