# Generated by Django 5.2.10 on 2026-01-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resumeanalysis_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='ats_score',
        ),
    ]
