# Generated by Django 5.2.10 on 2026-01-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_candidateprofile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='job_descriptions',
        ),
    ]
