# Generated by Django 5.2.10 on 2026-01-22 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_recruiterprofile_job_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='extracurricular_activities',
            field=models.TextField(blank=True, help_text='Extracurricular activities', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, help_text="Candidate's resume file", null=True, upload_to='candidate_resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Educational qualifications'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.IntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the candidate', max_length=255),
        ),
    ]
