# Generated by Django 5.2.10 on 2026-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
        migrations.AddField(
            model_name='job',
            name='job_descriptions',
            field=models.FileField(blank=True, help_text='job Descriptiona must include job title, responsibilities, qualifications, benefits, locations etc.', null=True, upload_to='job_descriptions/'),
        ),
    ]
