# Generated by Django 5.2.10 on 2026-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_job_description_job_job_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, help_text='Maximum salary for the job position', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, help_text='Minimum salary for the job position', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(help_text='Experience level required for the job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_descriptions',
            field=models.TextField(blank=True, help_text='Job Description for the position', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, help_text='List of required skills', null=True),
        ),
    ]
