# Generated by Django 5.2.10 on 2026-01-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERN', 'Intern'), ('REMOTE', 'Remote')], default='FULL_TIME', max_length=20),
        ),
    ]
