# Generated by Django 5.2.10 on 2026-01-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_descriptions',
            field=models.TextField(default='N/A', help_text='Job Description for the position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(default=0, help_text='Maximum salary for the job position'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(default=0, help_text='Minimum salary for the job position'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(default='N/A', help_text='List of required skills'),
            preserve_default=False,
        ),
    ]
